// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnv4LsaOoEESsumm31o3cI3-xrZJ2NIM',
    appId: '1:147207635468:web:18455257a00003f4062429',
    messagingSenderId: '147207635468',
    projectId: 'minichat-39a61',
    authDomain: 'minichat-39a61.firebaseapp.com',
    storageBucket: 'minichat-39a61.appspot.com',
    measurementId: 'G-8KBR3J08SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCubb--B1dJ_PWAPz3AymvtgRZvYgN3Qes',
    appId: '1:147207635468:android:b8f4b37f2d4d21eb062429',
    messagingSenderId: '147207635468',
    projectId: 'minichat-39a61',
    storageBucket: 'minichat-39a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6u02wRCI8DQfer1c5oKjp-XU00MVeSP0',
    appId: '1:147207635468:ios:e26727ded50b9592062429',
    messagingSenderId: '147207635468',
    projectId: 'minichat-39a61',
    storageBucket: 'minichat-39a61.appspot.com',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6u02wRCI8DQfer1c5oKjp-XU00MVeSP0',
    appId: '1:147207635468:ios:e26727ded50b9592062429',
    messagingSenderId: '147207635468',
    projectId: 'minichat-39a61',
    storageBucket: 'minichat-39a61.appspot.com',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSnv4LsaOoEESsumm31o3cI3-xrZJ2NIM',
    appId: '1:147207635468:web:b32b3b11e4531483062429',
    messagingSenderId: '147207635468',
    projectId: 'minichat-39a61',
    authDomain: 'minichat-39a61.firebaseapp.com',
    storageBucket: 'minichat-39a61.appspot.com',
    measurementId: 'G-TVW94NEN9S',
  );
}
